### ISSUE TITLE
Concert description page 

### ISSUE THREAD

**Issue by IFVG45** [Epsilon-JIJ/Concert-Concierge#13]
XD Prototype

**Comment by MissHockey15** [comment]
![1-first-pages](https://user-images.githubusercontent.com/16653330/35760287-440dd18e-084d-11e8-9976-d0c925ddc9e9.jpeg)
![3-calender](https://user-images.githubusercontent.com/16653330/35760288-44253f72-084d-11e8-8573-b75f35eae895.jpeg)
![2-concert pages](https://user-images.githubusercontent.com/16653330/35760289-44377bf6-084d-11e8-905c-c0c4e6cbd760.jpeg)

**Comment by MissHockey15** [comment]
Initial page, log in/sign up

![1-first-pages](https://user-images.githubusercontent.com/16653330/35760310-5a561d52-084d-11e8-8e6f-0f22d09c42c0.jpeg)
