### ISSUE TITLE
Sprint 4 Review

### ISSUE THREAD

**Issue by MissHockey15** [Epsilon-JIJ/Concert-Concierge#17]
Finished up prototyping and did user testing

**Comment by MissHockey15** [comment]
With the sketching done the previous week I took responsibility for designing the prototype for the mobile size of the website. Once the design was completed I handed it off to Iza to complete the prototyping and also looking over what I designed incase changes needed to be made. Once that was done I got a few users to test out the mobile and desktop versions of our web app. I got some feed back on the size of the font, buttons, concert cards, etc. It was mostly too small for mobile so those changes were noted.

**Comment by jsurtees** [comment]
User testing was completed. Main feedback was to clarify the signup process. There are two steps two signing in that seemed too similar. Now text has been added to clarify.

**Comment by IFVG45** [comment]
On sprint 4 Jaime handed me that final prototype to make any final changes and testing.  I was able to find some mistake and fixed them before handing it back to Jaime for any feedback or things I need to fix for the final testing. Getting more testing done could had helped us get changes noted faster.

**Comment by jsurtees** [comment]
@thomasjbradley
