### ISSUE TITLE
Sign up/Log In 

### ISSUE THREAD

**Issue by MissHockey15** [Epsilon-JIJ/Concert-Concierge#18]
[ ] We will be commencing the creation of the log in/sign up pages for Concert-Concierge. These pages will allow users to sign up for the web app and connect to their favourite music sources like Soundcloud, Apple Music, etc.

**Comment by IFVG45** [comment]
[XD files 3.zip](https://github.com/Epsilon-JIJ/Concert-Concierge/files/1732843/XD.files.3.zip)
