### ISSUE TITLE
Finalize writing content

### ISSUE THREAD

**Issue by IFVG45** [Epsilon-JIJ/Concert-Concierge#7]
- [ ] Come up with writing material by page

**Comment by MissHockey15** [comment]
1- Login instead to homepage(login sign up) - connection between other apps
CONCERT CONCIERGE  Planning your musical experience
Sign up or Log in
Get started
Sign up 
Name
Email
Password
Connect to Spotify, soundcloud, apple music, play music (or skip step)
Log in
Email
password
	
2- Concerts- List of concerts based on your favourite artist/Tracking location and favourite artists/link to
 Ticketmaster.
Near You, Your Artists, Recommended 
Concert
Name
Date/time
Place
Read more
Star icon
3-Concert description page
Photo of band
Name
Date/time
Place
Description of band
Preview music
Link to buy tickets
4- Planner (Calendar)
Sync with phone calendar
Header - The date
Cards underneath header for favourited concerts
